# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'custom.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(371, 331)
        self.lineEdit_1_1 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_1_1.setGeometry(QtCore.QRect(110, 130, 31, 21))
        self.lineEdit_1_1.setObjectName("lineEdit_1_1")
        self.lineEdit_1_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_1_2.setGeometry(QtCore.QRect(160, 130, 31, 21))
        self.lineEdit_1_2.setObjectName("lineEdit_1_2")
        self.lineEdit_1_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_1_3.setGeometry(QtCore.QRect(210, 130, 31, 21))
        self.lineEdit_1_3.setObjectName("lineEdit_1_3")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(80, 280, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(220, 280, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 331, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_2_1 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2_1.setGeometry(QtCore.QRect(110, 160, 31, 21))
        self.lineEdit_2_1.setObjectName("lineEdit_2_1")
        self.lineEdit_2_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2_3.setGeometry(QtCore.QRect(210, 160, 31, 21))
        self.lineEdit_2_3.setObjectName("lineEdit_2_3")
        self.lineEdit_2_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2_2.setGeometry(QtCore.QRect(160, 160, 31, 21))
        self.lineEdit_2_2.setObjectName("lineEdit_2_2")
        self.lineEdit_3_1 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3_1.setGeometry(QtCore.QRect(110, 190, 31, 21))
        self.lineEdit_3_1.setObjectName("lineEdit_3_1")
        self.lineEdit_3_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3_3.setGeometry(QtCore.QRect(210, 190, 31, 21))
        self.lineEdit_3_3.setObjectName("lineEdit_3_3")
        self.lineEdit_3_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3_2.setGeometry(QtCore.QRect(160, 190, 31, 21))
        self.lineEdit_3_2.setObjectName("lineEdit_3_2")
        self.lineEdit_0_1 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_0_1.setGeometry(QtCore.QRect(110, 90, 31, 21))
        self.lineEdit_0_1.setObjectName("lineEdit_0_1")
        self.lineEdit_0_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_0_3.setGeometry(QtCore.QRect(210, 90, 31, 21))
        self.lineEdit_0_3.setObjectName("lineEdit_0_3")
        self.lineEdit_0_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_0_2.setGeometry(QtCore.QRect(160, 90, 31, 21))
        self.lineEdit_0_2.setObjectName("lineEdit_0_2")
        self.lineEdit_4_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4_2.setGeometry(QtCore.QRect(160, 230, 31, 21))
        self.lineEdit_4_2.setObjectName("lineEdit_4_2")
        self.lineEdit_4_1 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4_1.setGeometry(QtCore.QRect(110, 230, 31, 21))
        self.lineEdit_4_1.setObjectName("lineEdit_4_1")
        self.lineEdit_4_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4_3.setGeometry(QtCore.QRect(210, 230, 31, 21))
        self.lineEdit_4_3.setObjectName("lineEdit_4_3")
        self.lineEdit_1_0 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_1_0.setGeometry(QtCore.QRect(60, 130, 31, 21))
        self.lineEdit_1_0.setObjectName("lineEdit_1_0")
        self.lineEdit_2_0 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2_0.setGeometry(QtCore.QRect(60, 160, 31, 21))
        self.lineEdit_2_0.setObjectName("lineEdit_2_0")
        self.lineEdit_0_0 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_0_0.setGeometry(QtCore.QRect(60, 90, 31, 21))
        self.lineEdit_0_0.setObjectName("lineEdit_0_0")
        self.lineEdit_3_0 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3_0.setGeometry(QtCore.QRect(60, 190, 31, 21))
        self.lineEdit_3_0.setObjectName("lineEdit_3_0")
        self.lineEdit_4_0 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4_0.setGeometry(QtCore.QRect(60, 230, 31, 21))
        self.lineEdit_4_0.setObjectName("lineEdit_4_0")
        self.lineEdit_1_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_1_4.setGeometry(QtCore.QRect(260, 130, 31, 21))
        self.lineEdit_1_4.setObjectName("lineEdit_1_4")
        self.lineEdit_2_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2_4.setGeometry(QtCore.QRect(260, 160, 31, 21))
        self.lineEdit_2_4.setObjectName("lineEdit_2_4")
        self.lineEdit_0_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_0_4.setGeometry(QtCore.QRect(260, 90, 31, 21))
        self.lineEdit_0_4.setObjectName("lineEdit_0_4")
        self.lineEdit_3_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3_4.setGeometry(QtCore.QRect(260, 190, 31, 21))
        self.lineEdit_3_4.setObjectName("lineEdit_3_4")
        self.lineEdit_4_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4_4.setGeometry(QtCore.QRect(260, 230, 31, 21))
        self.lineEdit_4_4.setObjectName("lineEdit_4_4")
        self.mdiArea_2 = QtWidgets.QMdiArea(Dialog)
        self.mdiArea_2.setGeometry(QtCore.QRect(50, 80, 251, 181))
        self.mdiArea_2.setStyleSheet("background-color: rgb(149, 149, 149);")
        self.mdiArea_2.setObjectName("mdiArea_2")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(100, 120, 151, 101))
        self.frame.setStyleSheet("background-color: rgb(211, 211, 211);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(10, 30, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.textBrowser.setFont(font)
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 280, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.mdiArea_2.raise_()
        self.frame.raise_()
        self.lineEdit_1_1.raise_()
        self.lineEdit_1_2.raise_()
        self.lineEdit_1_3.raise_()
        self.pushButton.raise_()
        self.pushButton_3.raise_()
        self.label.raise_()
        self.lineEdit_2_1.raise_()
        self.lineEdit_2_3.raise_()
        self.lineEdit_2_2.raise_()
        self.lineEdit_3_1.raise_()
        self.lineEdit_3_3.raise_()
        self.lineEdit_3_2.raise_()
        self.lineEdit_0_1.raise_()
        self.lineEdit_0_3.raise_()
        self.lineEdit_0_2.raise_()
        self.lineEdit_4_2.raise_()
        self.lineEdit_4_1.raise_()
        self.lineEdit_4_3.raise_()
        self.lineEdit_1_0.raise_()
        self.lineEdit_2_0.raise_()
        self.lineEdit_0_0.raise_()
        self.lineEdit_3_0.raise_()
        self.lineEdit_4_0.raise_()
        self.lineEdit_1_4.raise_()
        self.lineEdit_2_4.raise_()
        self.lineEdit_0_4.raise_()
        self.lineEdit_3_4.raise_()
        self.lineEdit_4_4.raise_()
        self.textBrowser.raise_()
        self.pushButton_2.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Costum Kernal"))
        self.pushButton.setText(_translate("Dialog", "5*5"))
        self.pushButton_3.setText(_translate("Dialog", "Cancel"))
        self.label.setText(_translate("Dialog", "Please Input the numbers in your costum filter here"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:9pt;\">if you want to design a 5*5 filter,fill all the boxes blow and push the 5*5 buuton.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:9pt;\">if you want to design a 3*3 filter,fill the 9 boxes in light gray and push the 3*3 buuton.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p></body></html>"))
        self.pushButton_2.setText(_translate("Dialog", "3*3"))

