# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MianWindow_zjp2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(1274, 889)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("border-color: rgb(72, 72, 72);")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(450, 20, 781, 791))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_4.setStyleSheet("background-color: rgb(59, 59, 59);")
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.gridLayout.addWidget(self.graphicsView_4, 1, 1, 1, 1)
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_2.setStyleSheet("background-color: rgb(59, 59, 59);")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayout.addWidget(self.graphicsView_2, 0, 1, 1, 1)
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_3.setStyleSheet("background-color: rgb(59, 59, 59);")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.gridLayout.addWidget(self.graphicsView_3, 1, 0, 1, 1)
        self.graphicsView_1 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_1.setStyleSheet("background-color: rgb(59, 59, 59);")
        self.graphicsView_1.setObjectName("graphicsView_1")
        self.gridLayout.addWidget(self.graphicsView_1, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(50, 20, 341, 841))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 510, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_6.setTextFormat(QtCore.Qt.PlainText)
        self.label_6.setObjectName("label_6")
        self.frame_3 = QtWidgets.QFrame(self.tab)
        self.frame_3.setGeometry(QtCore.QRect(0, 740, 301, 41))
        self.frame_3.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-color: rgb(124, 124, 124);\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalScrollBar_scale = QtWidgets.QScrollBar(self.frame_3)
        self.horizontalScrollBar_scale.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.horizontalScrollBar_scale.setStyleSheet("background-color: rgb(157, 157, 157);")
        self.horizontalScrollBar_scale.setMaximum(50)
        self.horizontalScrollBar_scale.setSingleStep(1)
        self.horizontalScrollBar_scale.setPageStep(5)
        self.horizontalScrollBar_scale.setSliderPosition(10)
        self.horizontalScrollBar_scale.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_scale.setObjectName("horizontalScrollBar_scale")
        self.label_scale_1 = QtWidgets.QLabel(self.frame_3)
        self.label_scale_1.setGeometry(QtCore.QRect(10, 0, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_scale_1.setFont(font)
        self.label_scale_1.setObjectName("label_scale_1")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(10, 480, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setObjectName("label_5")
        self.frame_4 = QtWidgets.QFrame(self.tab)
        self.frame_4.setGeometry(QtCore.QRect(10, 510, 281, 51))
        self.frame_4.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-color: rgb(124, 124, 124);\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushButton_sobel_y = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_sobel_y.setGeometry(QtCore.QRect(70, 20, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.pushButton_sobel_y.setFont(font)
        self.pushButton_sobel_y.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("OTSU")
        self.pushButton_sobel_y.setIcon(icon)
        self.pushButton_sobel_y.setObjectName("pushButton_sobel_y")
        self.pushButton_sobel_x = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_sobel_x.setGeometry(QtCore.QRect(10, 20, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.pushButton_sobel_x.setFont(font)
        self.pushButton_sobel_x.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("OTSU")
        self.pushButton_sobel_x.setIcon(icon)
        self.pushButton_sobel_x.setObjectName("pushButton_sobel_x")
        self.pushButton_previtt_x = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_previtt_x.setGeometry(QtCore.QRect(210, 20, 61, 23))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.pushButton_previtt_x.setFont(font)
        self.pushButton_previtt_x.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("OTSU")
        self.pushButton_previtt_x.setIcon(icon)
        self.pushButton_previtt_x.setObjectName("pushButton_previtt_x")
        self.pushButton_previtt_y = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_previtt_y.setGeometry(QtCore.QRect(140, 20, 61, 23))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.pushButton_previtt_y.setFont(font)
        self.pushButton_previtt_y.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("OTSU")
        self.pushButton_previtt_y.setIcon(icon)
        self.pushButton_previtt_y.setObjectName("pushButton_previtt_y")
        self.frame_5 = QtWidgets.QFrame(self.tab)
        self.frame_5.setGeometry(QtCore.QRect(10, 570, 181, 111))
        self.frame_5.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-color: rgb(124, 124, 124);\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.pushButton_gaussian = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_gaussian.setGeometry(QtCore.QRect(93, 21, 77, 24))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.pushButton_gaussian.setFont(font)
        self.pushButton_gaussian.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("OTSU")
        self.pushButton_gaussian.setIcon(icon)
        self.pushButton_gaussian.setObjectName("pushButton_gaussian")
        self.pushButton_meam = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_meam.setGeometry(QtCore.QRect(12, 21, 75, 24))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.pushButton_meam.setFont(font)
        self.pushButton_meam.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("OTSU")
        self.pushButton_meam.setIcon(icon)
        self.pushButton_meam.setObjectName("pushButton_meam")
        self.spinBox = QtWidgets.QSpinBox(self.frame_5)
        self.spinBox.setGeometry(QtCore.QRect(100, 50, 61, 22))
        self.spinBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox.setMinimum(1)
        self.spinBox.setSingleStep(2)
        self.spinBox.setProperty("value", 3)
        self.spinBox.setObjectName("spinBox")
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        self.label_8.setGeometry(QtCore.QRect(10, 50, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Footlight MT Light")
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        self.label_9.setGeometry(QtCore.QRect(10, 80, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Footlight MT Light")
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(10, 110, 171, 41))
        self.frame_2.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-color: rgb(124, 124, 124);\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.frame_2)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(10, 20, 141, 16))
        self.horizontalScrollBar.setStyleSheet("background-color: rgb(157, 157, 157);")
        self.horizontalScrollBar.setMaximum(255)
        self.horizontalScrollBar.setSliderPosition(100)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.label_threshold = QtWidgets.QLabel(self.frame_2)
        self.label_threshold.setGeometry(QtCore.QRect(10, 0, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_threshold.setFont(font)
        self.label_threshold.setObjectName("label_threshold")
        self.mdiArea = QtWidgets.QMdiArea(self.tab)
        self.mdiArea.setGeometry(QtCore.QRect(0, 50, 301, 411))
        self.mdiArea.setObjectName("mdiArea")
        self.frame_6 = QtWidgets.QFrame(self.tab)
        self.frame_6.setGeometry(QtCore.QRect(190, 60, 101, 91))
        self.frame_6.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-color: rgb(52, 52, 52);\n"
"\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_6)
        self.textBrowser.setGeometry(QtCore.QRect(10, 20, 81, 61))
        self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.label_result = QtWidgets.QLabel(self.frame_6)
        self.label_result.setGeometry(QtCore.QRect(10, 0, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_result.setFont(font)
        self.label_result.setObjectName("label_result")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(0, 720, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setObjectName("label_2")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBox.setGeometry(QtCore.QRect(110, 650, 62, 22))
        self.doubleSpinBox.setMaximum(10.0)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setProperty("value", 1.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(80, 30, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setObjectName("label_3")
        self.graphicsView_histogram = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView_histogram.setGeometry(QtCore.QRect(10, 170, 281, 281))
        self.graphicsView_histogram.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.graphicsView_histogram.setObjectName("graphicsView_histogram")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 30, 101, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(10, 60, 171, 41))
        self.frame.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-color: rgb(124, 124, 124);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_histogram = QtWidgets.QPushButton(self.frame)
        self.pushButton_histogram.setGeometry(QtCore.QRect(10, 10, 41, 23))
        self.pushButton_histogram.setStyleSheet("border-image: url(:/icon_his/icon_histogram.jpg);\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(208, 208, 208);")
        self.pushButton_histogram.setText("")
        self.pushButton_histogram.setObjectName("pushButton_histogram")
        self.pushButton_otsu = QtWidgets.QPushButton(self.frame)
        self.pushButton_otsu.setGeometry(QtCore.QRect(60, 10, 41, 23))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.pushButton_otsu.setFont(font)
        self.pushButton_otsu.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("OTSU")
        self.pushButton_otsu.setIcon(icon)
        self.pushButton_otsu.setObjectName("pushButton_otsu")
        self.pushButton_entropy = QtWidgets.QPushButton(self.frame)
        self.pushButton_entropy.setGeometry(QtCore.QRect(110, 10, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.pushButton_entropy.setFont(font)
        self.pushButton_entropy.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("OTSU")
        self.pushButton_entropy.setIcon(icon)
        self.pushButton_entropy.setObjectName("pushButton_entropy")
        self.pushButton_entropy.raise_()
        self.pushButton_otsu.raise_()
        self.pushButton_histogram.raise_()
        self.frame_7 = QtWidgets.QFrame(self.tab)
        self.frame_7.setGeometry(QtCore.QRect(200, 570, 91, 111))
        self.frame_7.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-color: rgb(124, 124, 124);\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.pushButton_custom = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_custom.setGeometry(QtCore.QRect(10, 60, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.pushButton_custom.setFont(font)
        self.pushButton_custom.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("OTSU")
        self.pushButton_custom.setIcon(icon)
        self.pushButton_custom.setObjectName("pushButton_custom")
        self.label_12 = QtWidgets.QLabel(self.frame_7)
        self.label_12.setGeometry(QtCore.QRect(10, 1, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_7)
        self.label_13.setGeometry(QtCore.QRect(10, 20, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_7)
        self.label_14.setGeometry(QtCore.QRect(10, 40, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.pushButton_custom_2 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_custom_2.setGeometry(QtCore.QRect(10, 80, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.pushButton_custom_2.setFont(font)
        self.pushButton_custom_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("OTSU")
        self.pushButton_custom_2.setIcon(icon)
        self.pushButton_custom_2.setObjectName("pushButton_custom_2")
        self.pushButton_custom_3 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_custom_3.setGeometry(QtCore.QRect(50, 80, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.pushButton_custom_3.setFont(font)
        self.pushButton_custom_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("OTSU")
        self.pushButton_custom_3.setIcon(icon)
        self.pushButton_custom_3.setObjectName("pushButton_custom_3")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(20, 570, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_7.setTextFormat(QtCore.Qt.PlainText)
        self.label_7.setObjectName("label_7")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(80, 480, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_4.setObjectName("label_4")
        self.mdiArea_2 = QtWidgets.QMdiArea(self.tab)
        self.mdiArea_2.setGeometry(QtCore.QRect(0, 500, 301, 201))
        self.mdiArea_2.setObjectName("mdiArea_2")
        self.mdiArea_2.raise_()
        self.frame_4.raise_()
        self.mdiArea.raise_()
        self.frame_3.raise_()
        self.label_5.raise_()
        self.frame_5.raise_()
        self.frame_2.raise_()
        self.frame_6.raise_()
        self.label_2.raise_()
        self.doubleSpinBox.raise_()
        self.label_3.raise_()
        self.graphicsView_histogram.raise_()
        self.label.raise_()
        self.frame.raise_()
        self.frame_7.raise_()
        self.label_7.raise_()
        self.label_4.raise_()
        self.label_6.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(80, 10, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_10.setTextFormat(QtCore.Qt.PlainText)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 101, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_11.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_11.setTextFormat(QtCore.Qt.PlainText)
        self.label_11.setObjectName("label_11")
        self.frame_8 = QtWidgets.QFrame(self.tab_2)
        self.frame_8.setGeometry(QtCore.QRect(150, 40, 131, 81))
        self.frame_8.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-color: rgb(124, 124, 124);\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.pushButton_erosion = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_erosion.setGeometry(QtCore.QRect(10, 20, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.pushButton_erosion.setFont(font)
        self.pushButton_erosion.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("OTSU")
        self.pushButton_erosion.setIcon(icon)
        self.pushButton_erosion.setObjectName("pushButton_erosion")
        self.pushButton_dilation = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_dilation.setGeometry(QtCore.QRect(70, 20, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.pushButton_dilation.setFont(font)
        self.pushButton_dilation.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("OTSU")
        self.pushButton_dilation.setIcon(icon)
        self.pushButton_dilation.setObjectName("pushButton_dilation")
        self.pushButton_opening = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_opening.setGeometry(QtCore.QRect(10, 50, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.pushButton_opening.setFont(font)
        self.pushButton_opening.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("OTSU")
        self.pushButton_opening.setIcon(icon)
        self.pushButton_opening.setObjectName("pushButton_opening")
        self.pushButton_closing = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_closing.setGeometry(QtCore.QRect(70, 50, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.pushButton_closing.setFont(font)
        self.pushButton_closing.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("OTSU")
        self.pushButton_closing.setIcon(icon)
        self.pushButton_closing.setObjectName("pushButton_closing")
        self.label_threshold_2 = QtWidgets.QLabel(self.frame_8)
        self.label_threshold_2.setGeometry(QtCore.QRect(10, 0, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_threshold_2.setFont(font)
        self.label_threshold_2.setObjectName("label_threshold_2")
        self.pushButton_erosion_2 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_erosion_2.setGeometry(QtCore.QRect(-120, 570, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.pushButton_erosion_2.setFont(font)
        self.pushButton_erosion_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("OTSU")
        self.pushButton_erosion_2.setIcon(icon)
        self.pushButton_erosion_2.setObjectName("pushButton_erosion_2")
        self.frame_10 = QtWidgets.QFrame(self.tab_2)
        self.frame_10.setGeometry(QtCore.QRect(10, 40, 121, 81))
        self.frame_10.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-color: rgb(124, 124, 124);\n"
"")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_threshold_3 = QtWidgets.QLabel(self.frame_10)
        self.label_threshold_3.setGeometry(QtCore.QRect(10, 0, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_threshold_3.setFont(font)
        self.label_threshold_3.setObjectName("label_threshold_3")
        self.radioButton_rect = QtWidgets.QRadioButton(self.frame_10)
        self.radioButton_rect.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.radioButton_rect.setChecked(True)
        self.radioButton_rect.setObjectName("radioButton_rect")
        self.radioButton_cross = QtWidgets.QRadioButton(self.frame_10)
        self.radioButton_cross.setGeometry(QtCore.QRect(10, 60, 51, 16))
        self.radioButton_cross.setObjectName("radioButton_cross")
        self.radioButton_ellipse = QtWidgets.QRadioButton(self.frame_10)
        self.radioButton_ellipse.setGeometry(QtCore.QRect(10, 40, 61, 16))
        self.radioButton_ellipse.setObjectName("radioButton_ellipse")
        self.mdiArea_3 = QtWidgets.QMdiArea(self.tab_2)
        self.mdiArea_3.setGeometry(QtCore.QRect(0, 30, 301, 461))
        self.mdiArea_3.setObjectName("mdiArea_3")
        self.frame_11 = QtWidgets.QFrame(self.tab_2)
        self.frame_11.setGeometry(QtCore.QRect(10, 130, 271, 61))
        self.frame_11.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-color: rgb(124, 124, 124);\n"
"")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_threshold_8 = QtWidgets.QLabel(self.frame_11)
        self.label_threshold_8.setGeometry(QtCore.QRect(10, 10, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_threshold_8.setFont(font)
        self.label_threshold_8.setObjectName("label_threshold_8")
        self.label_threshold_9 = QtWidgets.QLabel(self.frame_11)
        self.label_threshold_9.setGeometry(QtCore.QRect(160, 20, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_threshold_9.setFont(font)
        self.label_threshold_9.setObjectName("label_threshold_9")
        self.lineEdit_originx = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_originx.setGeometry(QtCore.QRect(220, 20, 21, 20))
        self.lineEdit_originx.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_originx.setObjectName("lineEdit_originx")
        self.lineEdit_originy = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_originy.setGeometry(QtCore.QRect(240, 20, 21, 20))
        self.lineEdit_originy.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_originy.setObjectName("lineEdit_originy")
        self.label_threshold_10 = QtWidgets.QLabel(self.frame_11)
        self.label_threshold_10.setGeometry(QtCore.QRect(220, 40, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_threshold_10.setFont(font)
        self.label_threshold_10.setObjectName("label_threshold_10")
        self.label_threshold_11 = QtWidgets.QLabel(self.frame_11)
        self.label_threshold_11.setGeometry(QtCore.QRect(10, 30, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_threshold_11.setFont(font)
        self.label_threshold_11.setObjectName("label_threshold_11")
        self.lineEdit_sizex = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_sizex.setGeometry(QtCore.QRect(80, 10, 21, 20))
        self.lineEdit_sizex.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_sizex.setObjectName("lineEdit_sizex")
        self.lineEdit_sizey = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_sizey.setGeometry(QtCore.QRect(80, 30, 21, 20))
        self.lineEdit_sizey.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_sizey.setObjectName("lineEdit_sizey")
        self.graphicsView_ori = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView_ori.setGeometry(QtCore.QRect(10, 210, 271, 271))
        self.graphicsView_ori.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.graphicsView_ori.setObjectName("graphicsView_ori")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(10, 500, 101, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_15.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_15.setTextFormat(QtCore.Qt.PlainText)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(80, 500, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_16.setTextFormat(QtCore.Qt.PlainText)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(100, 1140, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_17.setFont(font)
        self.label_17.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_17.setTextFormat(QtCore.Qt.PlainText)
        self.label_17.setObjectName("label_17")
        self.mdiArea_4 = QtWidgets.QMdiArea(self.tab_2)
        self.mdiArea_4.setGeometry(QtCore.QRect(80, 1130, 301, 201))
        self.mdiArea_4.setObjectName("mdiArea_4")
        self.mdiArea_5 = QtWidgets.QMdiArea(self.tab_2)
        self.mdiArea_5.setGeometry(QtCore.QRect(0, 520, 301, 101))
        self.mdiArea_5.setObjectName("mdiArea_5")
        self.frame_13 = QtWidgets.QFrame(self.tab_2)
        self.frame_13.setGeometry(QtCore.QRect(10, 530, 281, 81))
        self.frame_13.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-color: rgb(124, 124, 124);\n"
"")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.pushButton_distance_transform = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_distance_transform.setGeometry(QtCore.QRect(10, 10, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.pushButton_distance_transform.setFont(font)
        self.pushButton_distance_transform.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("OTSU")
        self.pushButton_distance_transform.setIcon(icon)
        self.pushButton_distance_transform.setObjectName("pushButton_distance_transform")
        self.pushButton_skeleton = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_skeleton.setGeometry(QtCore.QRect(10, 40, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.pushButton_skeleton.setFont(font)
        self.pushButton_skeleton.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("OTSU")
        self.pushButton_skeleton.setIcon(icon)
        self.pushButton_skeleton.setObjectName("pushButton_skeleton")
        self.pushButton_skeleton_restoration = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_skeleton_restoration.setGeometry(QtCore.QRect(70, 40, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.pushButton_skeleton_restoration.setFont(font)
        self.pushButton_skeleton_restoration.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("OTSU")
        self.pushButton_skeleton_restoration.setIcon(icon)
        self.pushButton_skeleton_restoration.setObjectName("pushButton_skeleton_restoration")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame_13)
        self.textBrowser_2.setGeometry(QtCore.QRect(200, 10, 71, 61))
        self.textBrowser_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.frame_9 = QtWidgets.QFrame(self.tab_2)
        self.frame_9.setGeometry(QtCore.QRect(10, 670, 131, 111))
        self.frame_9.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-color: rgb(124, 124, 124);\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalScrollBar_2 = QtWidgets.QScrollBar(self.frame_9)
        self.horizontalScrollBar_2.setGeometry(QtCore.QRect(10, 30, 101, 20))
        self.horizontalScrollBar_2.setStyleSheet("background-color: rgb(157, 157, 157);")
        self.horizontalScrollBar_2.setMaximum(255)
        self.horizontalScrollBar_2.setSliderPosition(100)
        self.horizontalScrollBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_2.setObjectName("horizontalScrollBar_2")
        self.label_threshold_6 = QtWidgets.QLabel(self.frame_9)
        self.label_threshold_6.setGeometry(QtCore.QRect(70, 10, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_threshold_6.setFont(font)
        self.label_threshold_6.setObjectName("label_threshold_6")
        self.label_threshold_7 = QtWidgets.QLabel(self.frame_9)
        self.label_threshold_7.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_threshold_7.setFont(font)
        self.label_threshold_7.setObjectName("label_threshold_7")
        self.label_threshold_16 = QtWidgets.QLabel(self.frame_9)
        self.label_threshold_16.setGeometry(QtCore.QRect(10, 60, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_threshold_16.setFont(font)
        self.label_threshold_16.setObjectName("label_threshold_16")
        self.pushButton = QtWidgets.QPushButton(self.frame_9)
        self.pushButton.setGeometry(QtCore.QRect(10, 80, 41, 23))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.mdiArea_6 = QtWidgets.QMdiArea(self.tab_2)
        self.mdiArea_6.setGeometry(QtCore.QRect(0, 660, 301, 131))
        self.mdiArea_6.setObjectName("mdiArea_6")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(80, 640, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_20.setTextFormat(QtCore.Qt.PlainText)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(10, 640, 101, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_21.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_21.setTextFormat(QtCore.Qt.PlainText)
        self.label_21.setObjectName("label_21")
        self.frame_24 = QtWidgets.QFrame(self.tab_2)
        self.frame_24.setGeometry(QtCore.QRect(150, 740, 131, 41))
        self.frame_24.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-color: rgb(124, 124, 124);\n"
"")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalScrollBar_scale_2 = QtWidgets.QScrollBar(self.frame_24)
        self.horizontalScrollBar_scale_2.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.horizontalScrollBar_scale_2.setStyleSheet("background-color: rgb(157, 157, 157);")
        self.horizontalScrollBar_scale_2.setMaximum(50)
        self.horizontalScrollBar_scale_2.setSingleStep(1)
        self.horizontalScrollBar_scale_2.setPageStep(5)
        self.horizontalScrollBar_scale_2.setSliderPosition(10)
        self.horizontalScrollBar_scale_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_scale_2.setObjectName("horizontalScrollBar_scale_2")
        self.label_scale_5 = QtWidgets.QLabel(self.frame_24)
        self.label_scale_5.setGeometry(QtCore.QRect(10, 0, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_scale_5.setFont(font)
        self.label_scale_5.setObjectName("label_scale_5")
        self.mdiArea_6.raise_()
        self.mdiArea_5.raise_()
        self.frame_13.raise_()
        self.mdiArea_3.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.frame_8.raise_()
        self.frame_10.raise_()
        self.frame_11.raise_()
        self.graphicsView_ori.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.mdiArea_4.raise_()
        self.frame_9.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.frame_24.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setGeometry(QtCore.QRect(80, 30, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_18.setTextFormat(QtCore.Qt.PlainText)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setGeometry(QtCore.QRect(10, 30, 101, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_19.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_19.setTextFormat(QtCore.Qt.PlainText)
        self.label_19.setObjectName("label_19")
        self.frame_12 = QtWidgets.QFrame(self.tab_3)
        self.frame_12.setGeometry(QtCore.QRect(10, 60, 121, 81))
        self.frame_12.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-color: rgb(124, 124, 124);\n"
"")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_threshold_4 = QtWidgets.QLabel(self.frame_12)
        self.label_threshold_4.setGeometry(QtCore.QRect(10, 0, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_threshold_4.setFont(font)
        self.label_threshold_4.setObjectName("label_threshold_4")
        self.radioButton_rect_gray = QtWidgets.QRadioButton(self.frame_12)
        self.radioButton_rect_gray.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.radioButton_rect_gray.setChecked(False)
        self.radioButton_rect_gray.setObjectName("radioButton_rect_gray")
        self.radioButton_cross_gray = QtWidgets.QRadioButton(self.frame_12)
        self.radioButton_cross_gray.setGeometry(QtCore.QRect(10, 60, 51, 16))
        self.radioButton_cross_gray.setObjectName("radioButton_cross_gray")
        self.radioButton_ellipse_gray = QtWidgets.QRadioButton(self.frame_12)
        self.radioButton_ellipse_gray.setGeometry(QtCore.QRect(10, 40, 61, 16))
        self.radioButton_ellipse_gray.setObjectName("radioButton_ellipse_gray")
        self.frame_15 = QtWidgets.QFrame(self.tab_3)
        self.frame_15.setGeometry(QtCore.QRect(150, 60, 131, 81))
        self.frame_15.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-color: rgb(124, 124, 124);\n"
"")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.pushButton_erosion_gray = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_erosion_gray.setGeometry(QtCore.QRect(10, 20, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.pushButton_erosion_gray.setFont(font)
        self.pushButton_erosion_gray.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("OTSU")
        self.pushButton_erosion_gray.setIcon(icon)
        self.pushButton_erosion_gray.setObjectName("pushButton_erosion_gray")
        self.pushButton_dilation_gray = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_dilation_gray.setGeometry(QtCore.QRect(70, 20, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.pushButton_dilation_gray.setFont(font)
        self.pushButton_dilation_gray.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("OTSU")
        self.pushButton_dilation_gray.setIcon(icon)
        self.pushButton_dilation_gray.setObjectName("pushButton_dilation_gray")
        self.pushButton_opening_gray = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_opening_gray.setGeometry(QtCore.QRect(10, 50, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.pushButton_opening_gray.setFont(font)
        self.pushButton_opening_gray.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("OTSU")
        self.pushButton_opening_gray.setIcon(icon)
        self.pushButton_opening_gray.setObjectName("pushButton_opening_gray")
        self.pushButton_closing_gray = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_closing_gray.setGeometry(QtCore.QRect(70, 50, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.pushButton_closing_gray.setFont(font)
        self.pushButton_closing_gray.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("OTSU")
        self.pushButton_closing_gray.setIcon(icon)
        self.pushButton_closing_gray.setObjectName("pushButton_closing_gray")
        self.label_threshold_5 = QtWidgets.QLabel(self.frame_15)
        self.label_threshold_5.setGeometry(QtCore.QRect(10, 0, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_threshold_5.setFont(font)
        self.label_threshold_5.setObjectName("label_threshold_5")
        self.graphicsView_ori_2 = QtWidgets.QGraphicsView(self.tab_3)
        self.graphicsView_ori_2.setGeometry(QtCore.QRect(10, 230, 271, 81))
        self.graphicsView_ori_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.graphicsView_ori_2.setObjectName("graphicsView_ori_2")
        self.mdiArea_7 = QtWidgets.QMdiArea(self.tab_3)
        self.mdiArea_7.setGeometry(QtCore.QRect(0, 50, 311, 281))
        self.mdiArea_7.setObjectName("mdiArea_7")
        self.frame_17 = QtWidgets.QFrame(self.tab_3)
        self.frame_17.setGeometry(QtCore.QRect(10, 150, 271, 61))
        self.frame_17.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-color: rgb(124, 124, 124);\n"
"")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.label_threshold_12 = QtWidgets.QLabel(self.frame_17)
        self.label_threshold_12.setGeometry(QtCore.QRect(10, 10, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_threshold_12.setFont(font)
        self.label_threshold_12.setObjectName("label_threshold_12")
        self.label_threshold_13 = QtWidgets.QLabel(self.frame_17)
        self.label_threshold_13.setGeometry(QtCore.QRect(160, 20, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_threshold_13.setFont(font)
        self.label_threshold_13.setObjectName("label_threshold_13")
        self.lineEdit_originx_gray = QtWidgets.QLineEdit(self.frame_17)
        self.lineEdit_originx_gray.setGeometry(QtCore.QRect(220, 20, 21, 20))
        self.lineEdit_originx_gray.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_originx_gray.setObjectName("lineEdit_originx_gray")
        self.lineEdit_originy_gray = QtWidgets.QLineEdit(self.frame_17)
        self.lineEdit_originy_gray.setGeometry(QtCore.QRect(240, 20, 21, 20))
        self.lineEdit_originy_gray.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_originy_gray.setObjectName("lineEdit_originy_gray")
        self.label_threshold_14 = QtWidgets.QLabel(self.frame_17)
        self.label_threshold_14.setGeometry(QtCore.QRect(220, 40, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_threshold_14.setFont(font)
        self.label_threshold_14.setObjectName("label_threshold_14")
        self.label_threshold_15 = QtWidgets.QLabel(self.frame_17)
        self.label_threshold_15.setGeometry(QtCore.QRect(10, 30, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_threshold_15.setFont(font)
        self.label_threshold_15.setObjectName("label_threshold_15")
        self.lineEdit_sizex_gray = QtWidgets.QLineEdit(self.frame_17)
        self.lineEdit_sizex_gray.setGeometry(QtCore.QRect(80, 10, 21, 20))
        self.lineEdit_sizex_gray.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_sizex_gray.setObjectName("lineEdit_sizex_gray")
        self.lineEdit_sizey_gray = QtWidgets.QLineEdit(self.frame_17)
        self.lineEdit_sizey_gray.setGeometry(QtCore.QRect(80, 30, 21, 20))
        self.lineEdit_sizey_gray.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_sizey_gray.setObjectName("lineEdit_sizey_gray")
        self.label_22 = QtWidgets.QLabel(self.tab_3)
        self.label_22.setGeometry(QtCore.QRect(10, 360, 101, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_22.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_22.setTextFormat(QtCore.Qt.PlainText)
        self.label_22.setObjectName("label_22")
        self.frame_14 = QtWidgets.QFrame(self.tab_3)
        self.frame_14.setGeometry(QtCore.QRect(10, 390, 141, 81))
        self.frame_14.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-color: rgb(124, 124, 124);\n"
"")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.pushButton_mor_edge = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_mor_edge.setGeometry(QtCore.QRect(80, 52, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.pushButton_mor_edge.setFont(font)
        self.pushButton_mor_edge.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("OTSU")
        self.pushButton_mor_edge.setIcon(icon)
        self.pushButton_mor_edge.setObjectName("pushButton_mor_edge")
        self.label_threshold_17 = QtWidgets.QLabel(self.frame_14)
        self.label_threshold_17.setGeometry(QtCore.QRect(10, 0, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_threshold_17.setFont(font)
        self.label_threshold_17.setObjectName("label_threshold_17")
        self.radioButton_edge_st = QtWidgets.QRadioButton(self.frame_14)
        self.radioButton_edge_st.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.radioButton_edge_st.setChecked(True)
        self.radioButton_edge_st.setObjectName("radioButton_edge_st")
        self.radioButton_edge_in = QtWidgets.QRadioButton(self.frame_14)
        self.radioButton_edge_in.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.radioButton_edge_in.setObjectName("radioButton_edge_in")
        self.radioButton_edge_ex = QtWidgets.QRadioButton(self.frame_14)
        self.radioButton_edge_ex.setGeometry(QtCore.QRect(10, 40, 71, 16))
        self.radioButton_edge_ex.setObjectName("radioButton_edge_ex")
        self.pushButton_mor_edge.raise_()
        self.label_threshold_17.raise_()
        self.radioButton_edge_st.raise_()
        self.radioButton_edge_in.raise_()
        self.radioButton_edge_ex.raise_()
        self.mdiArea_8 = QtWidgets.QMdiArea(self.tab_3)
        self.mdiArea_8.setGeometry(QtCore.QRect(0, 380, 311, 231))
        self.mdiArea_8.setObjectName("mdiArea_8")
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        self.label_23.setGeometry(QtCore.QRect(80, 360, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_23.setTextFormat(QtCore.Qt.PlainText)
        self.label_23.setObjectName("label_23")
        self.frame_16 = QtWidgets.QFrame(self.tab_3)
        self.frame_16.setGeometry(QtCore.QRect(160, 390, 141, 81))
        self.frame_16.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.frame_16.setToolTipDuration(-1)
        self.frame_16.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-color: rgb(124, 124, 124);\n"
"")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.pushButton_mor_gradient = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_mor_gradient.setGeometry(QtCore.QRect(80, 50, 61, 23))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.pushButton_mor_gradient.setFont(font)
        self.pushButton_mor_gradient.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("OTSU")
        self.pushButton_mor_gradient.setIcon(icon)
        self.pushButton_mor_gradient.setObjectName("pushButton_mor_gradient")
        self.label_threshold_20 = QtWidgets.QLabel(self.frame_16)
        self.label_threshold_20.setGeometry(QtCore.QRect(10, 0, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_threshold_20.setFont(font)
        self.label_threshold_20.setObjectName("label_threshold_20")
        self.radioButton_gradient_st = QtWidgets.QRadioButton(self.frame_16)
        self.radioButton_gradient_st.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.radioButton_gradient_st.setChecked(True)
        self.radioButton_gradient_st.setObjectName("radioButton_gradient_st")
        self.radioButton_gradient_in = QtWidgets.QRadioButton(self.frame_16)
        self.radioButton_gradient_in.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.radioButton_gradient_in.setObjectName("radioButton_gradient_in")
        self.radioButton_gradient_ex = QtWidgets.QRadioButton(self.frame_16)
        self.radioButton_gradient_ex.setGeometry(QtCore.QRect(10, 40, 71, 16))
        self.radioButton_gradient_ex.setObjectName("radioButton_gradient_ex")
        self.frame_18 = QtWidgets.QFrame(self.tab_3)
        self.frame_18.setEnabled(True)
        self.frame_18.setGeometry(QtCore.QRect(10, 480, 291, 111))
        self.frame_18.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-color: rgb(124, 124, 124);\n"
"")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.pushButton_reconstruction = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_reconstruction.setGeometry(QtCore.QRect(10, 10, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.pushButton_reconstruction.setFont(font)
        self.pushButton_reconstruction.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("OTSU")
        self.pushButton_reconstruction.setIcon(icon)
        self.pushButton_reconstruction.setObjectName("pushButton_reconstruction")
        self.pushButton_reconstruction_2 = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_reconstruction_2.setGeometry(QtCore.QRect(10, 40, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.pushButton_reconstruction_2.setFont(font)
        self.pushButton_reconstruction_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon.fromTheme("OTSU")
        self.pushButton_reconstruction_2.setIcon(icon)
        self.pushButton_reconstruction_2.setObjectName("pushButton_reconstruction_2")
        self.radioButton_cbr = QtWidgets.QRadioButton(self.frame_18)
        self.radioButton_cbr.setGeometry(QtCore.QRect(20, 70, 81, 16))
        self.radioButton_cbr.setChecked(True)
        self.radioButton_cbr.setObjectName("radioButton_cbr")
        self.radioButton_obr = QtWidgets.QRadioButton(self.frame_18)
        self.radioButton_obr.setGeometry(QtCore.QRect(20, 90, 71, 16))
        self.radioButton_obr.setObjectName("radioButton_obr")
        self.mdiArea_10 = QtWidgets.QMdiArea(self.tab_3)
        self.mdiArea_10.setGeometry(QtCore.QRect(0, 650, 311, 131))
        self.mdiArea_10.setObjectName("mdiArea_10")
        self.frame_22 = QtWidgets.QFrame(self.tab_3)
        self.frame_22.setGeometry(QtCore.QRect(10, 660, 131, 111))
        self.frame_22.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-color: rgb(124, 124, 124);\n"
"")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalScrollBar_threshold_gray = QtWidgets.QScrollBar(self.frame_22)
        self.horizontalScrollBar_threshold_gray.setGeometry(QtCore.QRect(10, 30, 101, 20))
        self.horizontalScrollBar_threshold_gray.setStyleSheet("background-color: rgb(157, 157, 157);")
        self.horizontalScrollBar_threshold_gray.setMaximum(255)
        self.horizontalScrollBar_threshold_gray.setSliderPosition(100)
        self.horizontalScrollBar_threshold_gray.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_threshold_gray.setObjectName("horizontalScrollBar_threshold_gray")
        self.label_threshold_30 = QtWidgets.QLabel(self.frame_22)
        self.label_threshold_30.setGeometry(QtCore.QRect(70, 10, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_threshold_30.setFont(font)
        self.label_threshold_30.setObjectName("label_threshold_30")
        self.label_threshold_31 = QtWidgets.QLabel(self.frame_22)
        self.label_threshold_31.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_threshold_31.setFont(font)
        self.label_threshold_31.setObjectName("label_threshold_31")
        self.label_threshold_32 = QtWidgets.QLabel(self.frame_22)
        self.label_threshold_32.setGeometry(QtCore.QRect(10, 60, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_threshold_32.setFont(font)
        self.label_threshold_32.setObjectName("label_threshold_32")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_22)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 80, 41, 23))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.frame_20 = QtWidgets.QFrame(self.tab_3)
        self.frame_20.setGeometry(QtCore.QRect(140, 820, 101, 41))
        self.frame_20.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-color: rgb(124, 124, 124);\n"
"")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalScrollBar_scale_3 = QtWidgets.QScrollBar(self.frame_20)
        self.horizontalScrollBar_scale_3.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.horizontalScrollBar_scale_3.setStyleSheet("background-color: rgb(157, 157, 157);")
        self.horizontalScrollBar_scale_3.setMaximum(50)
        self.horizontalScrollBar_scale_3.setSingleStep(1)
        self.horizontalScrollBar_scale_3.setPageStep(5)
        self.horizontalScrollBar_scale_3.setSliderPosition(10)
        self.horizontalScrollBar_scale_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_scale_3.setObjectName("horizontalScrollBar_scale_3")
        self.label_scale_3 = QtWidgets.QLabel(self.frame_20)
        self.label_scale_3.setGeometry(QtCore.QRect(10, 0, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_scale_3.setFont(font)
        self.label_scale_3.setObjectName("label_scale_3")
        self.label_26 = QtWidgets.QLabel(self.tab_3)
        self.label_26.setGeometry(QtCore.QRect(10, 630, 101, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_26.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_26.setTextFormat(QtCore.Qt.PlainText)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab_3)
        self.label_27.setGeometry(QtCore.QRect(80, 630, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_27.setTextFormat(QtCore.Qt.PlainText)
        self.label_27.setObjectName("label_27")
        self.frame_23 = QtWidgets.QFrame(self.tab_3)
        self.frame_23.setGeometry(QtCore.QRect(160, 730, 131, 41))
        self.frame_23.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-color: rgb(124, 124, 124);\n"
"")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalScrollBar_scale_gray = QtWidgets.QScrollBar(self.frame_23)
        self.horizontalScrollBar_scale_gray.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.horizontalScrollBar_scale_gray.setStyleSheet("background-color: rgb(157, 157, 157);")
        self.horizontalScrollBar_scale_gray.setMaximum(50)
        self.horizontalScrollBar_scale_gray.setSingleStep(1)
        self.horizontalScrollBar_scale_gray.setPageStep(5)
        self.horizontalScrollBar_scale_gray.setSliderPosition(10)
        self.horizontalScrollBar_scale_gray.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_scale_gray.setObjectName("horizontalScrollBar_scale_gray")
        self.label_scale_4 = QtWidgets.QLabel(self.frame_23)
        self.label_scale_4.setGeometry(QtCore.QRect(10, 0, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_scale_4.setFont(font)
        self.label_scale_4.setObjectName("label_scale_4")
        self.mdiArea_8.raise_()
        self.mdiArea_7.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.frame_12.raise_()
        self.frame_15.raise_()
        self.graphicsView_ori_2.raise_()
        self.frame_17.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.frame_14.raise_()
        self.radioButton_cross_gray.raise_()
        self.radioButton_ellipse_gray.raise_()
        self.radioButton_rect_gray.raise_()
        self.frame_16.raise_()
        self.frame_18.raise_()
        self.mdiArea_10.raise_()
        self.frame_22.raise_()
        self.frame_20.raise_()
        self.label_26.raise_()
        self.label_27.raise_()
        self.frame_23.raise_()
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1274, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuWorkspace = QtWidgets.QMenu(self.menubar)
        self.menuWorkspace.setObjectName("menuWorkspace")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuFunctions = QtWidgets.QMenu(self.menubar)
        self.menuFunctions.setObjectName("menuFunctions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionRecent_Main_Image = QtWidgets.QAction(MainWindow)
        self.actionRecent_Main_Image.setObjectName("actionRecent_Main_Image")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionProjrctq = QtWidgets.QAction(MainWindow)
        self.actionProjrctq.setObjectName("actionProjrctq")
        self.actionProject2 = QtWidgets.QAction(MainWindow)
        self.actionProject2.setObjectName("actionProject2")
        self.actionAbout_Me = QtWidgets.QAction(MainWindow)
        self.actionAbout_Me.setObjectName("actionAbout_Me")
        self.actionContact_Me = QtWidgets.QAction(MainWindow)
        self.actionContact_Me.setObjectName("actionContact_Me")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionHistogram = QtWidgets.QAction(MainWindow)
        self.actionHistogram.setObjectName("actionHistogram")
        self.actionManual_Segmentation = QtWidgets.QAction(MainWindow)
        self.actionManual_Segmentation.setObjectName("actionManual_Segmentation")
        self.actionOTSU_Segmentation = QtWidgets.QAction(MainWindow)
        self.actionOTSU_Segmentation.setObjectName("actionOTSU_Segmentation")
        self.actionEntropy_Method_Segmentation = QtWidgets.QAction(MainWindow)
        self.actionEntropy_Method_Segmentation.setObjectName("actionEntropy_Method_Segmentation")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionRecent_Main_Image)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuWorkspace.addAction(self.actionProjrctq)
        self.menuWorkspace.addAction(self.actionProject2)
        self.menuHelp.addAction(self.actionAbout_Me)
        self.menuHelp.addAction(self.actionContact_Me)
        self.menuFunctions.addAction(self.actionHistogram)
        self.menuFunctions.addAction(self.actionManual_Segmentation)
        self.menuFunctions.addAction(self.actionOTSU_Segmentation)
        self.menuFunctions.addAction(self.actionEntropy_Method_Segmentation)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuFunctions.menuAction())
        self.menubar.addAction(self.menuWorkspace.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Processing"))
        self.label_6.setText(_translate("MainWindow", "Edge"))
        self.label_scale_1.setText(_translate("MainWindow", "scale1"))
        self.label_5.setText(_translate("MainWindow", "ToolBox "))
        self.pushButton_sobel_y.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Segment the picture into background and foreground using OTSU method</p></body></html>"))
        self.pushButton_sobel_y.setText(_translate("MainWindow", "Sobel-y"))
        self.pushButton_sobel_y.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.pushButton_sobel_x.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Segment the picture into background and foreground using OTSU method</p></body></html>"))
        self.pushButton_sobel_x.setText(_translate("MainWindow", "Sobel-x"))
        self.pushButton_sobel_x.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.pushButton_previtt_x.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Segment the picture into background and foreground using OTSU method</p></body></html>"))
        self.pushButton_previtt_x.setText(_translate("MainWindow", "Previtt-y"))
        self.pushButton_previtt_x.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.pushButton_previtt_y.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Segment the picture into background and foreground using OTSU method</p></body></html>"))
        self.pushButton_previtt_y.setText(_translate("MainWindow", "Previtt-x"))
        self.pushButton_previtt_y.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.pushButton_gaussian.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Segment the picture into background and foreground using OTSU method</p></body></html>"))
        self.pushButton_gaussian.setText(_translate("MainWindow", "Gaussion"))
        self.pushButton_gaussian.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.pushButton_meam.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Segment the picture into background and foreground using OTSU method</p></body></html>"))
        self.pushButton_meam.setText(_translate("MainWindow", "Mean"))
        self.pushButton_meam.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.label_8.setText(_translate("MainWindow", "Set Gaussian Size"))
        self.label_9.setText(_translate("MainWindow", "Set Guassian sigma"))
        self.label_threshold.setText(_translate("MainWindow", "Threshold"))
        self.label_result.setText(_translate("MainWindow", "Threshold Display"))
        self.label_2.setText(_translate("MainWindow", "Adjustment"))
        self.label_3.setText(_translate("MainWindow", "In Project1"))
        self.label.setText(_translate("MainWindow", "ToolBox "))
        self.pushButton_histogram.setToolTip(_translate("MainWindow", "<html><head/><body><p>QT designer</p></body></html>"))
        self.pushButton_otsu.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Segment the picture into background and foreground using OTSU method</p></body></html>"))
        self.pushButton_otsu.setText(_translate("MainWindow", "OTSU"))
        self.pushButton_otsu.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.pushButton_entropy.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Segment the picture into background and foreground using OTSU method</p></body></html>"))
        self.pushButton_entropy.setText(_translate("MainWindow", "Entropy"))
        self.pushButton_entropy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.pushButton_custom.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Segment the picture into background and foreground using OTSU method</p></body></html>"))
        self.pushButton_custom.setText(_translate("MainWindow", "Here!"))
        self.pushButton_custom.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.label_12.setText(_translate("MainWindow", "Custom"))
        self.label_13.setText(_translate("MainWindow", "Convolution"))
        self.label_14.setText(_translate("MainWindow", "Kernal?"))
        self.pushButton_custom_2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Segment the picture into background and foreground using OTSU method</p></body></html>"))
        self.pushButton_custom_2.setText(_translate("MainWindow", "3*3"))
        self.pushButton_custom_2.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.pushButton_custom_3.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Segment the picture into background and foreground using OTSU method</p></body></html>"))
        self.pushButton_custom_3.setText(_translate("MainWindow", "5*5"))
        self.pushButton_custom_3.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.label_7.setText(_translate("MainWindow", "Denoise/Smooth"))
        self.label_4.setText(_translate("MainWindow", "In Project2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Project 1, 2"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">1</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "In Project3"))
        self.label_11.setText(_translate("MainWindow", "ToolBox "))
        self.pushButton_erosion.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Segment the picture into background and foreground using OTSU method</p></body></html>"))
        self.pushButton_erosion.setText(_translate("MainWindow", "Erosion"))
        self.pushButton_erosion.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.pushButton_dilation.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Segment the picture into background and foreground using OTSU method</p></body></html>"))
        self.pushButton_dilation.setText(_translate("MainWindow", "Dilation"))
        self.pushButton_dilation.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.pushButton_opening.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Segment the picture into background and foreground using OTSU method</p></body></html>"))
        self.pushButton_opening.setText(_translate("MainWindow", "Opening"))
        self.pushButton_opening.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.pushButton_closing.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Segment the picture into background and foreground using OTSU method</p></body></html>"))
        self.pushButton_closing.setText(_translate("MainWindow", "Closing"))
        self.pushButton_closing.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.label_threshold_2.setText(_translate("MainWindow", "Basic Operation"))
        self.pushButton_erosion_2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Segment the picture into background and foreground using OTSU method</p></body></html>"))
        self.pushButton_erosion_2.setText(_translate("MainWindow", "Erosion"))
        self.pushButton_erosion_2.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.label_threshold_3.setText(_translate("MainWindow", "Kernal shape"))
        self.radioButton_rect.setText(_translate("MainWindow", "Rect"))
        self.radioButton_cross.setText(_translate("MainWindow", "Cross"))
        self.radioButton_ellipse.setText(_translate("MainWindow", "Ellipse"))
        self.label_threshold_8.setText(_translate("MainWindow", "Kernal size_x"))
        self.label_threshold_9.setText(_translate("MainWindow", "Origin Point"))
        self.lineEdit_originx.setText(_translate("MainWindow", "1"))
        self.lineEdit_originy.setText(_translate("MainWindow", "1"))
        self.label_threshold_10.setText(_translate("MainWindow", "  x     y"))
        self.label_threshold_11.setText(_translate("MainWindow", "Kernal size_y"))
        self.lineEdit_sizex.setText(_translate("MainWindow", "3"))
        self.lineEdit_sizey.setText(_translate("MainWindow", "3"))
        self.label_15.setText(_translate("MainWindow", "ToolBox "))
        self.label_16.setText(_translate("MainWindow", "In Project4"))
        self.label_17.setText(_translate("MainWindow", "Edge"))
        self.pushButton_distance_transform.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Segment the picture into background and foreground using OTSU method</p></body></html>"))
        self.pushButton_distance_transform.setText(_translate("MainWindow", "Distance Transform"))
        self.pushButton_distance_transform.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.pushButton_skeleton.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Segment the picture into background and foreground using OTSU method</p></body></html>"))
        self.pushButton_skeleton.setText(_translate("MainWindow", "Skeleton"))
        self.pushButton_skeleton.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.pushButton_skeleton_restoration.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Segment the picture into background and foreground using OTSU method</p></body></html>"))
        self.pushButton_skeleton_restoration.setText(_translate("MainWindow", "Skeleton Restoration"))
        self.pushButton_skeleton_restoration.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.label_threshold_6.setText(_translate("MainWindow", "Threshold"))
        self.label_threshold_7.setText(_translate("MainWindow", "binarization"))
        self.label_threshold_16.setText(_translate("MainWindow", "White & Black"))
        self.pushButton.setText(_translate("MainWindow", "Invert"))
        self.label_20.setText(_translate("MainWindow", "assistant"))
        self.label_21.setText(_translate("MainWindow", "ToolBox "))
        self.label_scale_5.setText(_translate("MainWindow", "scale1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Project3,4"))
        self.label_18.setText(_translate("MainWindow", "In Project5"))
        self.label_19.setText(_translate("MainWindow", "ToolBox "))
        self.label_threshold_4.setText(_translate("MainWindow", "Kernal shapes"))
        self.radioButton_rect_gray.setText(_translate("MainWindow", "Rect"))
        self.radioButton_cross_gray.setText(_translate("MainWindow", "Cross"))
        self.radioButton_ellipse_gray.setText(_translate("MainWindow", "Ellipse"))
        self.pushButton_erosion_gray.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Segment the picture into background and foreground using OTSU method</p></body></html>"))
        self.pushButton_erosion_gray.setText(_translate("MainWindow", "Erosion"))
        self.pushButton_erosion_gray.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.pushButton_dilation_gray.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Segment the picture into background and foreground using OTSU method</p></body></html>"))
        self.pushButton_dilation_gray.setText(_translate("MainWindow", "Dilation"))
        self.pushButton_dilation_gray.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.pushButton_opening_gray.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Segment the picture into background and foreground using OTSU method</p></body></html>"))
        self.pushButton_opening_gray.setText(_translate("MainWindow", "Opening"))
        self.pushButton_opening_gray.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.pushButton_closing_gray.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Segment the picture into background and foreground using OTSU method</p></body></html>"))
        self.pushButton_closing_gray.setText(_translate("MainWindow", "Closing"))
        self.pushButton_closing_gray.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.label_threshold_5.setText(_translate("MainWindow", "Basic Operation"))
        self.label_threshold_12.setText(_translate("MainWindow", "Kernal size_x"))
        self.label_threshold_13.setText(_translate("MainWindow", "Origin Point"))
        self.lineEdit_originx_gray.setText(_translate("MainWindow", "1"))
        self.lineEdit_originy_gray.setText(_translate("MainWindow", "1"))
        self.label_threshold_14.setText(_translate("MainWindow", "  x     y"))
        self.label_threshold_15.setText(_translate("MainWindow", "Kernal size_y"))
        self.lineEdit_sizex_gray.setText(_translate("MainWindow", "3"))
        self.lineEdit_sizey_gray.setText(_translate("MainWindow", "3"))
        self.label_22.setText(_translate("MainWindow", "ToolBox "))
        self.pushButton_mor_edge.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Segment the picture into background and foreground using OTSU method</p></body></html>"))
        self.pushButton_mor_edge.setText(_translate("MainWindow", "Edge"))
        self.pushButton_mor_edge.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.label_threshold_17.setText(_translate("MainWindow", "edge types"))
        self.radioButton_edge_st.setText(_translate("MainWindow", "standard"))
        self.radioButton_edge_in.setText(_translate("MainWindow", "internal"))
        self.radioButton_edge_ex.setText(_translate("MainWindow", "external"))
        self.label_23.setText(_translate("MainWindow", "In Project6"))
        self.pushButton_mor_gradient.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Segment the picture into background and foreground using OTSU method</p></body></html>"))
        self.pushButton_mor_gradient.setText(_translate("MainWindow", "Gradient"))
        self.pushButton_mor_gradient.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.label_threshold_20.setText(_translate("MainWindow", "gradient types"))
        self.radioButton_gradient_st.setText(_translate("MainWindow", "standard"))
        self.radioButton_gradient_in.setText(_translate("MainWindow", "internal"))
        self.radioButton_gradient_ex.setText(_translate("MainWindow", "external"))
        self.pushButton_reconstruction.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Segment the picture into background and foreground using OTSU method</p></body></html>"))
        self.pushButton_reconstruction.setText(_translate("MainWindow", "Morthology Reconstructionin in binary image"))
        self.pushButton_reconstruction.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.pushButton_reconstruction_2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Segment the picture into background and foreground using OTSU method</p></body></html>"))
        self.pushButton_reconstruction_2.setText(_translate("MainWindow", "Morthology Reconstructionin in gray image"))
        self.pushButton_reconstruction_2.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.radioButton_cbr.setText(_translate("MainWindow", "CBR"))
        self.radioButton_obr.setText(_translate("MainWindow", "OBR"))
        self.label_threshold_30.setText(_translate("MainWindow", "Threshold"))
        self.label_threshold_31.setText(_translate("MainWindow", "binarization"))
        self.label_threshold_32.setText(_translate("MainWindow", "White & Black"))
        self.pushButton_5.setText(_translate("MainWindow", "Invert"))
        self.label_scale_3.setText(_translate("MainWindow", "scale1"))
        self.label_26.setText(_translate("MainWindow", "ToolBox "))
        self.label_27.setText(_translate("MainWindow", "assistant"))
        self.label_scale_4.setText(_translate("MainWindow", "scale1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Project5,6"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuWorkspace.setTitle(_translate("MainWindow", "Workspace"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuFunctions.setTitle(_translate("MainWindow", "Functions"))
        self.actionOpen.setText(_translate("MainWindow", "Open Main Image"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionRecent_Main_Image.setText(_translate("MainWindow", "Recent Main Image"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionProjrctq.setText(_translate("MainWindow", "Projrct1"))
        self.actionProject2.setText(_translate("MainWindow", "Project2"))
        self.actionAbout_Me.setText(_translate("MainWindow", "About Me"))
        self.actionContact_Me.setText(_translate("MainWindow", "Contact Me"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionHistogram.setText(_translate("MainWindow", "Histogram"))
        self.actionManual_Segmentation.setText(_translate("MainWindow", "Manual Segmentation"))
        self.actionOTSU_Segmentation.setText(_translate("MainWindow", "OTSU Segmentation"))
        self.actionEntropy_Method_Segmentation.setText(_translate("MainWindow", "Entropy Method Segmentation"))

import icon_histogram2_rc
